/* same thing as asset 1 but generated by llm  *//* 
This first attempt uses absolute value coordinates, using the view height and width as info 
*/

import { Node, Path, Rect, makeScene2D, Spline } from '@motion-canvas/2d';
import { createRef, waitFor, all } from '@motion-canvas/core';
import { SVG } from '@motion-canvas/2d/lib/components/SVG';
import personSVG from '/svg_assets/person-wave-svgrepo-com.svg?raw';
import bulbSVG from '/svg_assets/light-bulb-line-drawing-svgrepo-com.svg?raw'
import { recurseNodes } from '../utils_tree';

export default makeScene2D(function* (view) {
  const leftNode = createRef<Node>();
  const rightNode = createRef<Node>();
  const container = createRef<Rect>();
  const bulbNode = createRef<Node>();
  const targetRect = createRef<Rect>();
  const centerLine = createRef<Spline>();
  const svgPersonRef = createRef<SVG>();
  const svgBulbRef = createRef<SVG>();

  view.fill('#000000');

  const targetWidth = view.width() / 3;
  const targetHeight = view.height() / 3;
  
  view.add(
    <Rect ref={container}>
        <Node
          ref={leftNode}
          x={-view.width() / 4}
        >
          <SVG svg={personSVG} size={300} scale={0} opacity={0} ref={svgPersonRef} />
        </Node>
        <Spline ref={centerLine} endArrow={true} stroke={'white'} lineWidth={5} start={0} end={0} opacity={0} />
        <Node
          ref={rightNode}
          x={view.width() / 4}
        >
          <Rect
            ref={targetRect}
            stroke={'red'}
            lineWidth={5}
            fill={'black'}
          />
        </Node>
        <Node ref={bulbNode} x={() => {
          const pos_leftNode = leftNode().absolutePosition().transformAsPoint(container().worldToLocal())
          return pos_leftNode.x
        }} y={-view.width() / 5}>
          <SVG svg={bulbSVG} size={150} scale={0} opacity={0} ref={svgBulbRef} />
        </Node>
    </Rect>
  );

  yield* waitFor(.5);
  
  // Animate SVG elements
  const svgElements = [svgPersonRef(), svgBulbRef()]
  const animations = [];
  
  for (const svgElement of svgElements) {
    animations.push(svgElement.scale(1, .5));
    animations.push(svgElement.opacity(1, .5));
    for (const child of svgElement.children()[0].children()) {
      if (child instanceof Path) {
        child.fill('white');
      }
    }
  }

  yield* all(...animations);

  // Animate target rectangles
  for (let child of recurseNodes(container())) {
    if (child instanceof Rect && child != container()) {
      yield* all(...[child.fill('red', 1), child.width(targetWidth, 1), child.height(targetHeight, 1)]);
    }
  }
})